### ISSUE TITLE
Permalinks and Media Routes

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#13]
- [x] Media routes /media/{seriesSlug}/{messageSlug}
- [ ] Default all routes to use slug

**Comment by camrun91** [comment]
This is working in the test enviroment. I am not 100% positive that it is working as we intended but you can navigate to /media/{ANYTHING}/a-church-that-reconciles and it works.

**Comment by camrun91** [comment]
@wesgate this is now working with /media/seriesslug/mediaslug. 

I think we will have to set up the routes to take a slug on each page/route.
