### ISSUE TITLE
Login Status

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#17]
Get the login status button working up in the nav section. Rock looks to already have a login status block we can utilize

**Comment by camrun91** [comment]
I have pushed changes to this that get them to display. 
@wesgate will need to help line up the css values to get everything to line up right.

**Comment by wesgate** [comment]
@camrun91 I committed new changes that I believe will fix the styling for the login status

**Comment by camrun91** [comment]
@wesgate This appears to be working in the test environment. I will push the changes to prod and see if I can get it working there then close this.

**Comment by camrun91** [comment]
@wesgate this is working there is one bug though. When I log out it gets rid of the outline and just says login.

**Comment by wesgate** [comment]
@camrun91 got it. should be fixed now
