### ISSUE TITLE
Search Indexing

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#18]
What system to use for search indexing. Elasticsearch vs Google Search

**Comment by camrun91** [comment]
I implemented the search using Lucerne the built in search in rock. We need to do some styling on the page and styling of the results.

**Comment by camrun91** [comment]
Need to evaluate this and see if Elastic search would be a better option. Elastic search may allow us to manage the index and add more "Weight" to specific items.

**Comment by camrun91** [comment]
I have moved this over to an Elastic search instance. This should us to add weights.
