### ISSUE TITLE
Ministries as Pages or Content Channel

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#22]
Currently they are setup to feed from a content channel.  It is the most flexible to query, however, the page templates themselves can be less flexible. You use one page template to show all of the details for a ministry so it doesn't seem like you can modify the layout per ministry (why pages would be better in that case).

**Comment by camrun91** [comment]
Per our Flow chart/diagram a lot of the ministry info will not be specific pages but instead, info included on other pages. This can be discussed more to nail down the exact details.

**Comment by camrun91** [comment]
I am not sure that all ministries need pages. Matt is thinking of getting the children's/nursery info on the location pages.
