### ISSUE TITLE
Separate Latest Message Button into its own Shortcode

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#26]
@racingcow 

Not sure if this is the best one to start with but take a look and let me know.

Essentially, a new message is put out every week. There are several places that we place a button with "Watch Latest Message" and we need it to be reusable and dynamic to always link to the latest message.

Therefore, we need to use a shortcode that will produce a button with a link to the latest message. We can duplicate our current 'button' shortcode and just name this one {[ latestMessageButton ]}. Alternatively, we could alter the button shortcode to have a boolean param for latestmessage and then use that as a trigger to set the link to the latest message or not.

FYI - all shortcode parameters have to be all lowercase (took me a while to figure that out) Example: {[button buttontext:"Click Here" ]} 'buttontext' must be all lowercase

The tricky part of this is figuring out the best way to get the latest message. i can think of 3 ways but haven't investigated yet.

1) Use a lava query within the shortcode to search content channel items of Sermon Message and grab the first one that has an Active Date greater than today. (this may be the simplest, but i dont know how performant it is, but may be the best place to start). it will be something like this I think:

{% contentchannelitem where:'ContentChannelId == 5' && Status.Value == "Approved" && StartDateTime.Value > Now' | First %}
    {% for item in contentchannelitemItems %}
        	{{item.Title}}
	{% endfor %}
{% endcontentchannelitem %}

That channel ID is just an example I saw, not sure if we could do it by name (using an ID will be different between prod and dev is my concern)

2) Add a Global Attribute that is of a type of Content Channel Item (if possible limit it to Sermon Messages) and assign the Global Attribute to the latest Sermon Message. Then we could grab that attribute and it should deliver the latest message information (title, description, ids or routes to make the url, etc)

3) Use a SQL query that gets the latest message and stores that in a persisted dataset

**Comment by wesgate** [comment]
@camrun91 if you have any other ways to approach it off the top of your head, just let us know

**Comment by racingcow** [comment]
@wesgate I went with option 1, and think it's getting close. I noticed that the sermon messages seem to be getting cached, which took me a while to figure out, as it made it look like the sorting wasn't working.

It still needs a few cleanup items, like filtering for Active messages, and I'll try and make a db update script for it. Take a look and see if you see anything else that needs changes, or if you'd rather me switch to a different option.

Commit is here https://github.com/CrossingsCommunityChurch/RockTheme/commit/61b0e6a2410755f804fe4be470fae639c9367d77

**Comment by camrun91** [comment]
I added one comment to that commit just a question on the URL that you are pulling. It looks like the link is to vimeo. We want the user to stay on our site if we can.

**Comment by racingcow** [comment]
Yeah, @camrun91 , I figured I'd change that in another pass after the button looked good. For night now, it's just opening Vimeo in another window.

It looks like that maybe I should move the user to page 461 and pass the contentItemId of the sermon message in the query string, as in http://localhost:50886/page/461?Item=<contentItemId>. Is that right?

**Comment by wesgate** [comment]
@racingcow @camrun91 

That is one way (and may be the way we had it initially with the query param), but I in the end we are actually going to want to pull the slug and use that as the url (hopefully that is just latest.Slug?). So it will actually be something like:

http://localhost:50886/media/{contentItemSlug}

The Media Details page should be setup to handle a route like that and I added the route in Routes as well.

Eventually, we need to figure out the routing to do this:
http://localhost:50886/media/{sermonSeriesSlug or ParentSlug}/{contentItemSlug}
but we are not there yet

Wes

**Comment by camrun91** [comment]
Yeah that sounds like that is what we need to do. Should not be a big deal to do later.

**Comment by racingcow** [comment]
Okay. I updated such that the URL will now be `/media/{sermonSeriesSlug}/{messageSlug}`. If there is no parent sermon series for some reason, it will use `no-series` as a default. Let me know if I should change that to something else.

**Comment by racingcow** [comment]
It looks like nothing is required for db data changes in this either, since it's really just the `button.lava` code that has changed. I'll submit a pull request. Let me know if either of you see anything out of place, @wesgate and @camrun91.

Also let me know if there is another issue that I can get started on.

**Comment by wesgate** [comment]
@racingcow Looks good, I merged the PR
