### ISSUE TITLE
Shouldn't tags be on the Message level?

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#30]

**Comment by camrun91** [comment]
Yes this is a setting on the content channel. So we are able to enable and disable it on each content channel individually. This has been done on the Sermon Message and teaching series message.

**Comment by wesgate** [comment]
@camrun91 - sounds good. now that tags and speaker are on the messages, do you think you an Brett can find some folks to start going through and assigning speakers and tags to them. Do you think we should setup two categories of tags to be available for messages?  (one that is topics, and another that is books of the bible. that way we should be able to filter them out easier when we are trying to query them )

Also, when you get a chance, can you push up the latest?

I made some changes to fix vimeo stuff and also am pulling the vimeo image url if it is assigned, it that is not assigned it will fall back to using the Image Asset that is on the message level to display in the listings.

You can see the listings here (dont have pagination on there yet)
https://rock.crossings.church/media

They should all link to a media details page that will pull in the message details.

Another point with that is the Message Content. We are generally pulling that over for a brief summary to be displayed. It pulled in the description from vimeo which is fine, but it has quite a bit of extra content we wont need like the date, website url and speaker. We either need folks to clean that up so that it is just a summary, or we can create another attribute to use for the summary

Wes

**Comment by camrun91** [comment]
Yes, I will pull down the latest changes and then I will get with Matt and his team to have them start cleaning up the content and adding tags and speakers. 

As far as the books of the bible. I think for the app that will be used in the app from the Scripture Reference key-value pair with the key not being used. However, if this is something that we want to change we certainly can change that.
