### ISSUE TITLE
Account Pages Styling

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#40]
Need to style the account pages /MyAccount

**Comment by camrun91** [comment]
I started to try and build out the pages using lava, however I think it would be better if we just styled the default block that is used. It looks like it is doing lots of data queries and saving them. So @wesgate if you are able to lets try and style the default block elements on the profile page.

**Comment by wesgate** [comment]
@camrun91 I pushed up CSS changes to style the account pages. I will need to make some changes on production to get all of the styles working since I added a couple classes here and there in the lava to help make the styling a little easier

Wes

**Comment by wesgate** [comment]
Login
Account Registration
Account Confirmation
Forgot Password
Change Password
My Account
	- Group Toolbox
404
Photo Uplaod
Communication

**Comment by camrun91** [comment]
I just pulled them down so feel free to make the changes you need to make.
