### ISSUE TITLE
View.js in media page

### ISSUE THREAD

**Issue by racingcow** [CrossingsCommunityChurch/RockTheme#65]
@racingcow - of course, all this talk of filtering and rest endpoints makes me really want to add vuejs to the project and just use it for the media listings. I know it adds some bloat but it may be worth considering. It's pretty much the lightest weight of its kind and only 35kb when gzipped and it could add some cool reactivity to the media page. Just running a little vue app for the media list essentially. You guys have any thoughts? i of course am a fan, but let me know if you think it's not a good idea.

_Originally posted by @wesgate in https://github.com/CrossingsCommunityChurch/RockTheme/issues/48#issuecomment-666871809_

**Comment by racingcow** [comment]
@wesgate and @camrun91 ,

I'm going to use this issue to track work on the media page. As I understand it, we want to try and do these things...

- Make the media page load in items without refreshing the page
- Use true Ajax calls instead of loading all of the items up-front as we've done on the Events page.
- Try and use View.js

Let me know if there are any other things to consider here.

**Comment by racingcow** [comment]
@wesgate @camrun91 

One of the things we'll need to make Vue work is some kind of API call that we can securely access from client-side javascript. I've explored a few things and wanted to write them in here in case any of us need to come back and look at this in the future...

I first looked at the Rock API, but it doesn't have a way to get our combined media messages in a single call. Making a bunch of calls on the client side and then doing joins and merges in JS would be pretty slow.

Then I looked at using [Remote Lava](https://community.rockrms.com/lava/remote-lava), but there isn't really a good way to secure it. It works without an API key if you are logged in, but our users need to access this anonymously, and there isn't any way to securely store a secret like an API key in JS. If we use Remote Lava, pretty much anyone could query anything in the database, so that option is out.

I think the best option here is to use the [Lava Webhook](http://localhost:50886/page/119?definedTypeId=65) Defined Type. If you add a Defined Value to that Type that is an arbitrary route, like `crossings/api/combined-media`, then define a Lava Template for it, Rock will run that template and return the results to any anonymous caller. There is no security around it, but it will only return what we tell it, and as long as we're calling from JS on the same domain there shouldn't be any CORS stuff to worry about. So as long as we are careful to restrict the data in our Lava, it should be fine for our purposes.

I've defined that route, so if you point a browser to the webhook (link below), it should return the combined media results as JSON (I'm using port 50886 to debug locally). Unless you guys see any issues with it, I'll try and hook some Vue stuff up to use that "endpoint" next.

http://localhost:50886/Webhooks/Lava.ashx/crossings/api/combined-media

![image](https://user-images.githubusercontent.com/1176637/89725610-840a9d80-d9ce-11ea-8a0d-f62f252090b6.png)

![image](https://user-images.githubusercontent.com/1176637/89725603-6806fc00-d9ce-11ea-933b-1a0dba573c31.png)

**Comment by wesgate** [comment]
That looks to work well for me David. The response on the call is quick as well because it is pulling from that persisted dataset. I switched it to use Combinedmedia (because I think that is the one you want) - mediaSeriesCombined i believe is one we abandoned. ‘Combinedmedia' should have all your filterLists as well as all media. I think you could just take that one call and then take the response and setup “data” as you need to in the little vue app

Wes

**Comment by racingcow** [comment]
Thanks for reminding me about the `mediaSeriesCombined` ones being obsolete, @wesgate. I keep getting those two confused. Do you mind if I delete that one, or is there something else you know of that is using it?

**Comment by wesgate** [comment]
Yeah, feel free to remove it so we don't get confused

Thanks!

Wes

**Comment by racingcow** [comment]
@camrun91  @wesgate ,

Hey, just wanted to give a quick update on this one since it's been a while. I have a test page working that uses Vue to load the results from that Lava Webhook on creation and will page through the results on the client side. I still need to get filtering working and put it back into the real media page.

One funky thing is that Lava/Liquid uses the same mustache-style templating delimiters that Vue does. So any double curly braces that you're trying to use for Vue get replaced with empty strings (essentially deleting them) on the server side before client-side Vue gets a chance to do its thing. To work around, you have to put  "raw" tags around them in the Lava code like this... 

```javascript
{% raw %} {{ myVueInterpolatedValue }} {% endraw %}
```

It seems to work, though.

I'm also using just direct script references to the Vue, Axios, etc. JS files via a CDN rather than using the Vue CLI or otherwise to pull in Webpack, etc. Let me know if I should change that.

```html
{% javascript id:'vue' url:'https://cdn.jsdelivr.net/combine/npm/vue@2.6.11/dist/vue.js,npm/axios@0.19.2/dist/axios.js' %}
{% endjavascript %}
```

**Comment by wesgate** [comment]
@racingcow - sounds good David, for now, just leave the cdn reference. I have thought about adding in a bundler/compiler to create 1 js file for all of that, but for now, the script references should be fine.

i hadn't even thought about the mustache-style templating issue there. Probably a little annoying to have to use the {% raw %} tags but the 'template' portion of the vue component probably isn't too crazy

**Comment by racingcow** [comment]
Okay, @wesgate  and @camrun91 . I think I finally have a [working PR](https://github.com/CrossingsCommunityChurch/RockTheme/pull/67) for this. As always, let me know of any issues that you find.

**Comment by wesgate** [comment]
@racingcow I think this looks good david, i am going to merge it and maybe make a few ui changes.

**Comment by racingcow** [comment]
Sounds good, @wesgate . Let me know if you there is another item that I can work on, such as going back and putting Vue in the events page.

**Comment by wesgate** [comment]
@racingcow hey david, i will let you know if we decide to try and fit that in and get back to you

one other thought i had was similar to that of the hal smith private dining site we made where changed the url to use params when filtering and used that to filter by so folks could essentially share a filtered list through a url, but I don't know if that is quite as necessary in this case, I will let you know
