### ISSUE TITLE
Mobile nav gets hidden on apple devices without home button.

### ISSUE THREAD

**Issue by camrun91** [CrossingsCommunityChurch/RockTheme#66]
On Apple devices, without the home button, the mobile nav is behind the bar for the swipe up gesture. This causes all nav buttons to have to be pressed two times to work.

**Comment by wesgate** [comment]
https://www.eventbrite.com/engineering/mobile-safari-why/

**Comment by camrun91** [comment]
I noticed that a lot of sites do this I do not think this is a problem. Closing it now.
