### ISSUE TITLE
Search Bar for Media

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#78]
@racingcow 

i made a change to the filtering/search for media so be sure and grab the latest. The lists for topics and speakers and books of the bible were getting long so we are swapping the dropdowns for a search bar that folks can just type into. The church opted to not do a filter for books of the bible so I removed that.

I changed the filter to a search bar that looks for topics, title, series, speaker name and then filters the list from that. Feel free to go in and optimize what I did because what you had was a lot cleaner, I just couldn't get it to work the way I needed it to when trying to use an open-ended search box as the filter key

One item that I didnt handle that would be good is if we could look at tags and filter by "starts with" instead of using the include for for the array item and making someone have to search the entire tag name to get it to show. Hopefully that makes sense. Essentially if someone searches Fai it should include tags that have been tagged with Faith

Another thing I didn't do yet that I was hoping you could handle that I think would be cool is if we can suggest a topic or the name of a speaker below when someone is typing. So for example if someone typed: 'F', it would give them suggested searches for **F**aith, Terry **F**eix, (words that start with F). We may need to be a little more selective so it may need to be like 2 characters or something as a minimum, but basically just trying to mimic what google does with suggested searches below the input

Let me know if you have any questions on that

Wes

**Comment by wesgate** [comment]
@racingcow 

One more thing on this one... we need a way to link back to this page and pre-filter the results from a search query (just for tags). So essentially we need something like this media/?tag={tagName} to set the search box value and filter the results on load

Then we can set urls on the tags that are displayed on the sermon pages and link back to this page and automatically filter the results based on the query string

Wes

**Comment by racingcow** [comment]
Thanks @wesgate . I will take a look at this one.

**Comment by racingcow** [comment]
@wesgate ,

I think #79 addresses all of the items here. Let me know if you see anything fishy with it.

-David

**Comment by camrun91** [comment]
@racingcow @wesgate Hey this is not a high priority for "go live" But having a search bar on the events would be nice.

**Comment by racingcow** [comment]
> @racingcow @wesgate Hey this is not a high priority for "go live" But having a search bar on the events would be nice.

@camrun91 @wesgate ,

Sure, I can do something similar to what we've done here on the events page, if that makes sense. Let me know if that works for you and I will put in another issue and start working on it.

**Comment by camrun91** [comment]
Yeah that would be perfect! Thanks

**Comment by wesgate** [comment]
Closing old issues
