### ISSUE TITLE
Search bar on the events page

### ISSUE THREAD

**Issue by racingcow** [CrossingsCommunityChurch/RockTheme#81]
@racingcow @wesgate Hey this is not a high priority for "go live" But having a search bar on the events would be nice.

_Originally posted by @camrun91 in https://github.com/CrossingsCommunityChurch/RockTheme/issues/78#issuecomment-686566643_

**Comment by racingcow** [comment]
@wesgate  and @camrun91 ,

Have a look at the PR at https://github.com/CrossingsCommunityChurch/RockTheme/pull/82. I think it gives us a search input for events, similar to the media page. It also has both pages use a common slotted component.

**Comment by wesgate** [comment]
Closing old issues
